/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Region = IDL.Record({
  'id' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
});
export const SchoolCategory = IDL.Variant({
  'sd' : IDL.Null,
  'smk' : IDL.Null,
  'smp' : IDL.Null,
  'smaK' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Attendance = IDL.Record({
  'checkIn' : Time,
  'checkOut' : Time,
  'photo' : ExternalBlob,
});
export const School = IDL.Record({
  'id' : IDL.Nat,
  'region' : Region,
  'submissionsCount' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'lastSubmissionDate' : IDL.Opt(Time),
  'principalId' : IDL.Principal,
  'schoolCategory' : SchoolCategory,
});
export const SubmissionCategory = IDL.Variant({
  'classControl' : IDL.Null,
  'problemSolving' : IDL.Null,
  'teacherControl' : IDL.Null,
  'programExecution' : IDL.Null,
  'parentResponse' : IDL.Null,
  'attendance' : IDL.Null,
});
export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'classControl' : IDL.Bool,
  'problemSolving' : IDL.Text,
  'teacherControl' : IDL.Bool,
  'date' : Time,
  'programExecution' : IDL.Bool,
  'parentResponse' : IDL.Bool,
  'score' : IDL.Nat,
  'schoolId' : IDL.Nat,
  'attendance' : IDL.Opt(Attendance),
  'category' : SubmissionCategory,
  'principalId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'region' : Region,
  'displayName' : IDL.Text,
  'role' : IDL.Text,
  'schoolName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignKepsekProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, Region],
      [],
      [],
    ),
  'createSchool' : IDL.Func(
      [IDL.Text, Region, SchoolCategory, IDL.Principal],
      [IDL.Nat],
      [],
    ),
  'createSubmission' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(Attendance),
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getActiveSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalActiveSchools' : IDL.Nat,
          'submissionsToday' : IDL.Nat,
          'averageScore' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getSchoolDetails' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'school' : School,
          'recentSubmissions' : IDL.Vec(Submission),
        }),
      ],
      ['query'],
    ),
  'getSchoolsByRegion' : IDL.Func([IDL.Nat], [IDL.Vec(School)], ['query']),
  'getSubmissionsBySchool' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'getTopSchools' : IDL.Func([IDL.Nat], [IDL.Vec(School)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSchool' : IDL.Func(
      [IDL.Nat, IDL.Text, Region, SchoolCategory, IDL.Principal, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Region = IDL.Record({
    'id' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
  });
  const SchoolCategory = IDL.Variant({
    'sd' : IDL.Null,
    'smk' : IDL.Null,
    'smp' : IDL.Null,
    'smaK' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Attendance = IDL.Record({
    'checkIn' : Time,
    'checkOut' : Time,
    'photo' : ExternalBlob,
  });
  const School = IDL.Record({
    'id' : IDL.Nat,
    'region' : Region,
    'submissionsCount' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'lastSubmissionDate' : IDL.Opt(Time),
    'principalId' : IDL.Principal,
    'schoolCategory' : SchoolCategory,
  });
  const SubmissionCategory = IDL.Variant({
    'classControl' : IDL.Null,
    'problemSolving' : IDL.Null,
    'teacherControl' : IDL.Null,
    'programExecution' : IDL.Null,
    'parentResponse' : IDL.Null,
    'attendance' : IDL.Null,
  });
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'classControl' : IDL.Bool,
    'problemSolving' : IDL.Text,
    'teacherControl' : IDL.Bool,
    'date' : Time,
    'programExecution' : IDL.Bool,
    'parentResponse' : IDL.Bool,
    'score' : IDL.Nat,
    'schoolId' : IDL.Nat,
    'attendance' : IDL.Opt(Attendance),
    'category' : SubmissionCategory,
    'principalId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'region' : Region,
    'displayName' : IDL.Text,
    'role' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignKepsekProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, Region],
        [],
        [],
      ),
    'createSchool' : IDL.Func(
        [IDL.Text, Region, SchoolCategory, IDL.Principal],
        [IDL.Nat],
        [],
      ),
    'createSubmission' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(Attendance),
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getActiveSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalActiveSchools' : IDL.Nat,
            'submissionsToday' : IDL.Nat,
            'averageScore' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getSchoolDetails' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'school' : School,
            'recentSubmissions' : IDL.Vec(Submission),
          }),
        ],
        ['query'],
      ),
    'getSchoolsByRegion' : IDL.Func([IDL.Nat], [IDL.Vec(School)], ['query']),
    'getSubmissionsBySchool' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'getTopSchools' : IDL.Func([IDL.Nat], [IDL.Vec(School)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSchool' : IDL.Func(
        [IDL.Nat, IDL.Text, Region, SchoolCategory, IDL.Principal, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };