/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'checkIn' : Time,
  'checkOut' : Time,
  'photo' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface Region { 'id' : bigint, 'code' : string, 'name' : string }
export interface School {
  'id' : bigint,
  'region' : Region,
  'submissionsCount' : bigint,
  'name' : string,
  'isActive' : boolean,
  'lastSubmissionDate' : [] | [Time],
  'principalId' : Principal,
  'schoolCategory' : SchoolCategory,
}
export type SchoolCategory = { 'sd' : null } |
  { 'smk' : null } |
  { 'smp' : null } |
  { 'smaK' : null };
export interface Submission {
  'id' : bigint,
  'classControl' : boolean,
  'problemSolving' : string,
  'teacherControl' : boolean,
  'date' : Time,
  'programExecution' : boolean,
  'parentResponse' : boolean,
  'score' : bigint,
  'schoolId' : bigint,
  'attendance' : [] | [Attendance],
  'category' : SubmissionCategory,
  'principalId' : Principal,
}
export type SubmissionCategory = { 'classControl' : null } |
  { 'problemSolving' : null } |
  { 'teacherControl' : null } |
  { 'programExecution' : null } |
  { 'parentResponse' : null } |
  { 'attendance' : null };
export type Time = bigint;
export interface UserProfile {
  'region' : Region,
  'displayName' : string,
  'role' : string,
  'schoolName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignKepsekProfile' : ActorMethod<
    [Principal, string, string, Region],
    undefined
  >,
  'createSchool' : ActorMethod<
    [string, Region, SchoolCategory, Principal],
    bigint
  >,
  'createSubmission' : ActorMethod<
    [bigint, [] | [Attendance], boolean, boolean, boolean, boolean, string],
    bigint
  >,
  'getActiveSchools' : ActorMethod<[], Array<School>>,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalActiveSchools' : bigint,
      'submissionsToday' : bigint,
      'averageScore' : bigint,
    }
  >,
  'getMySubmissions' : ActorMethod<[], Array<Submission>>,
  'getSchoolDetails' : ActorMethod<
    [bigint],
    { 'school' : School, 'recentSubmissions' : Array<Submission> }
  >,
  'getSchoolsByRegion' : ActorMethod<[bigint], Array<School>>,
  'getSubmissionsBySchool' : ActorMethod<[bigint], Array<Submission>>,
  'getTopSchools' : ActorMethod<[bigint], Array<School>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSchool' : ActorMethod<
    [bigint, string, Region, SchoolCategory, Principal, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];